// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5MYiKre46WDYsxo1TTE0TYxYI6itobR8',
    appId: '1:457922620005:web:8f3d06bc8b2ccbd799348c',
    messagingSenderId: '457922620005',
    projectId: 'chatapp-f617d',
    authDomain: 'chatapp-f617d.firebaseapp.com',
    databaseURL: 'https://chatapp-f617d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-f617d.appspot.com',
    measurementId: 'G-2G3YX9DJQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE83sgoXte4X7F6gFgwY1rlCeRwgR2JMQ',
    appId: '1:457922620005:android:cc311295f20c585899348c',
    messagingSenderId: '457922620005',
    projectId: 'chatapp-f617d',
    databaseURL: 'https://chatapp-f617d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-f617d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn227hqw0nGlPjH1HG0yEEk4RS7Mle8xM',
    appId: '1:457922620005:ios:b96ada8c1569fa1d99348c',
    messagingSenderId: '457922620005',
    projectId: 'chatapp-f617d',
    databaseURL: 'https://chatapp-f617d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-f617d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn227hqw0nGlPjH1HG0yEEk4RS7Mle8xM',
    appId: '1:457922620005:ios:45a562273f6aafae99348c',
    messagingSenderId: '457922620005',
    projectId: 'chatapp-f617d',
    databaseURL: 'https://chatapp-f617d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-f617d.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
